### ISSUE TITLE
Work in 1.19.2 ??

### ISSUE THREAD

**Issue by luucfr** [timiliris/New_Gui_ServerSelector_blue_gold#2]
![image](https://user-images.githubusercontent.com/49595636/205508945-6198308a-c9c1-43b8-a91a-d98a8b87092e.png)

**Comment by timiliris** [comment]
hi , yes it's work on 1.19.2 but i'think item adder  have update they folder management , then if use latest version off item adders u can find some issue like that i've not start working on the new version of item adder because i'm currently workind on a production server

**Comment by luucfr** [comment]
I found the solution!

In the menu configuration in BetterGUI
```
menu-settings:
  name: '&f%img_offset_-12%%img_server_selector%'  #<-- Here
  inventory-type: CHEST
  rows: 6
  command: game
  auto-refresh: 5
```
By

```
menu-settings:
  name: '&f%img_offset_-12%%server_selector%'  #<-- Here 
  inventory-type: CHEST
  rows: 6
  command: game
  auto-refresh: 5
```
